apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  type: LoadBalancer
  loadBalancerIP: 'change-me'
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    role: rproxy
